import pandas as pd

# --- CONFIGURAZIONE ---
INPUT_FILE = "alimenti.csv"
OUTPUT_FILE = "alimenti_completo.csv"
SEPARATOR = ";"          # Cambia in ";" se il tuo CSV usa il punto e virgola

# 1. Leggi il file CSV
df = pd.read_csv(INPUT_FILE, sep=SEPARATOR)

# 2. Visualizza le colonne disponibili
print("Colonne disponibili:")
for i, col in enumerate(df.columns):
    print(f"  [{i}] {col}")

print(f"\nDimensioni dataframe: {df.shape[0]} righe x {df.shape[1]} colonne")
print("\nAnteprima (prime 3 righe):")
print(df.head(3))

# 3. Seleziona il sottoinsieme di colonne
# OPZIONE A: specifica i nomi delle colonne direttamente
COLONNE_SELEZIONATE = [
"name",
"category",
"food_code",
"scientific_name",
"english_name",
"info",
"samples_number",
"edible_part",
"portion",
"image",
"water",
"energy_kcal",
"energy_kj",
"proteins",
"lipids",
"cholesterol",
"available_carbohydrates",
"starch",
"soluble_sugars",
"alcohol",
"total_fiber",
"soluble_fiber",
"insoluble_fiber",
"sucrose",
"glucose",
"fructose",
"lactose",
"galactose",
"maltose",
"maltotriosium",
"raffinose",
"fluorine",
"sodium",
"magnesium",
"phosphorus",
"chlorine",
"potassium",
"calcium",
"chromium",
"manganese",
"iron",
"nickel",
"copper",
"zinc",
"selenium",
"iodine",
"total_carotenoids",
"alpha_carotene",
"beta_carotene",
"cryptoxanthin",
"lycopene",
"lutein",
"retinol",
"zeaxanthin",
"vitamin_a_retinol_equivalent",
"thiamine",
"riboflavin",
"niacin",
"pantothenic_acid",
"vitamin_b6",
"biotin",
"folate",
"vitamin_b12",
"vitamin_c",
"vitamin_d",
"vitamin_e",
"alpha_tocopherol",
"beta_tocopherol",
"gamma_tocopherol",
"delta_tocopherol",
"vitamin_k",
"Saturated_fatty_acids",
"C4:0-C10:0",
"C4:0_butyric_acid",
"C6:0_capronic_acid",
"C7:0_enanthic_acid",
"C8:0_caprylic_acid",
"C10:0_caprinic_acid",
"C12:0_lauric_acid",
"C13:0_tridecanoic_acid",
"C14:0_myristic_acid",
"C15:0_pentadecanoic_acid",
"C16:0_palmitic_acid",
"C17:0_heptadecanoic_acid",
"C18:0_stearic_acid",
"C20:0_arachidic_acid",
"C22:0_behenic_acid",
"C24:0_lignoceric_acid",
"monounsaturated_fatty_acids",
"C10:1_caproleic_acid",
"C12:1_lauroleic_acid",
"C13:1_tridecenoic_acid",
"C14:1_myristoleic_acid",
"C15:1_pentadecenoic_acid",
"C16:1 palmitoleic_acid",
"C17:1_heptadecenoic_acid",
"C18:1_oleic_acid",
"C20:1_eicosenoic_acid",
"C22:1_erucic_acid",
"polyunsaturated_fatty_acids",
"C18:2_linoleic_acid",
"C18:3_linolenic_acid",
"C20:4_arachidonic_acid",
"C20:5_eicosapentaenoic_acid_EPA",
"C22:6_docosahexaenoic_acid_DHA",
"polyunsaturated_saturated",
"alanine",
"cystine",
"aspartic_acid",
"glutamic_acid",
"phenylalanine",
"glycine",
"histidine",
"isoleucine",
"lysine",
"leucine",
"methionine",
"proline",
"arginine",
"serine",
"threonine",
"valine",
"tryptophan",
"tyrosine",
"chemical_index",
"limiting_amino_acid",
"caffeic_acid",
"citric_acid",
"phytic_acid",
"malic_acid",
"apigenin",
"antioxidant_activity",
"campferol",
"phytosterols",
"fructo-oligosaccharides",
"myricetin",
"polyphenols",
"quercetin",
"violaxanthin"
] # <-- modifica qui
COLONNE_RINOMINATE = [
"nome",
"categoria",
"codice_alimento",
"nome_scientifico",
"nome_inglese",
"info",
"numero_campioni",
"parte_edibile",
"porzione",
"immagine",
"acqua",
"energia_kcal",
"energia_kj",
"proteine",
"lipidi",
"colesterolo",
"carboidrati_disponibili",
"amido",
"zuccheri_solubili",
"alcol",
"fibra_totale",
"fibra_solubile",
"fibra_insolubile",
"saccarosio",
"glucosio",
"fruttosio",
"lattosio",
"galattosio",
"maltosio",
"maltotriosio",
"raffinosio",
"fluoro",
"sodio",
"magnesio",
"fosforo",
"cloro",
"potassio",
"calcio",
"cromo",
"manganese",
"ferro",
"nichel",
"rame",
"zinco",
"selenio",
"iodio",
"carotenoidi_totali",
"alfa_carotene",
"beta_carotene",
"criptoxantina",
"licopene",
"luteina",
"retinolo",
"zeaxantina",
"vitamina_a_equivalenti_retinolo",
"tiamina",
"riboflavina",
"niacina",
"acido_pantotenico",
"vitamina_b6",
"biotina",
"folati",
"vitamina_b12",
"vitamina_c",
"vitamina_d",
"vitamina_e",
"alfa_tocoferolo",
"beta_tocoferolo",
"gamma_tocoferolo",
"delta_tocoferolo",
"vitamina_k",
"acidi_grassi_saturi",
"C4:0-C10:0",
"C4:0_acido_butirrico",
"C6:0_acido_capronico",
"C7:0_acido_enantico",
"C8:0_acido_caprilico",
"C10:0_acido_caprinico",
"C12:0_acido_laurico",
"C13:0_acido_tridecanoico",
"C14:0_acido_miristico",
"C15:0_acido_pentadecanoico",
"C16:0_acido_palmitico",
"C17:0_acido_eptadecanoico",
"C18:0_acido_stearico",
"C20:0_acido_arachidico",
"C22:0_acido_behenico",
"C24:0_acido_lignocerico",
"acidi_grassi_monoinsaturi",
"C10:1_acido_caproleico",
"C12:1_acido_lauroleico",
"C13:1_acido_tridecenoico",
"C14:1_acido_miristoleico",
"C15:1_acido_pentadecenoico",
"C16:1_acido_palmitoleico",
"C17:1_acido_eptadecenoico",
"C18:1_acido_oleico",
"C20:1_acido_eicosenoico",
"C22:1_acido_erucico",
"acidi_grassi_polinsaturi",
"C18:2_acido_linoleico",
"C18:3_acido_linolenico",
"C20:4_acido_arachidonico",
"C20:5_acido_eicosapentaenoico_EPA",
"C22:6_acido_docosaesaenoico_DHA",
"rapporto_polinsaturi_saturi",
"alanina",
"cistina",
"acido_aspartico",
"acido_glutammico",
"fenilalanina",
"glicina",
"istidina",
"isoleucina",
"lisina",
"leucina",
"metionina",
"prolina",
"arginina",
"serina",
"treonina",
"valina",
"triptofano",
"tirosina",
"indice_chimico",
"aminoacido_limitante",
"acido_caffeico",
"acido_citrico",
"acido_fitico",
"acido_malico",
"apigenina",
"attivita_antiossidante",
"kaempferolo",
"fitosteroli",
"frutto-oligosaccaridi",
"miricetina",
"polifenoli",
"quercetina",
"violaxantina"
]  # <-- modifica qui

# OPZIONE B: seleziona per indice (decommenta le righe sotto e commenta OPZIONE A)
# INDICI_COLONNE = [0, 1, 2, 11, 13, 14, 16, 18 ,20,21,22]
# COLONNE_SELEZIONATE = df.columns[INDICI_COLONNE].tolist()

df_filtrato = df[COLONNE_SELEZIONATE]
df_filtrato.columns = COLONNE_RINOMINATE

for i in list(df_filtrato["nome"].index):
    if df_filtrato['carboidrati_disponibili'][i] == None:
        df_filtrato['carboidrati_disponibili'][i] = 0
    else:
        df_filtrato['carboidrati_disponibili'][i] /= 10
    
    if df_filtrato['proteine'][i] == None:
        df_filtrato['proteine'][i] = 0
    else:
        df_filtrato['proteine'][i] /= 10

    if df_filtrato['lipidi'][i] == None:
        df_filtrato['lipidi'][i] = 0
print("Valori aggiustati")
print(f"\nColonne selezionate: {COLONNE_SELEZIONATE}")
print(f"Dimensioni dataframe filtrato: {df_filtrato.shape[0]} righe x {df_filtrato.shape[1]} colonne")

# 4. Salva il nuovo CSV
df_filtrato.to_csv(OUTPUT_FILE, sep=SEPARATOR, index=False)
print(f"\nFile salvato in: {OUTPUT_FILE}")

COLONNE_SELEZIONATE2 = [
"nome",
"categoria",
"energia_kcal",
"energia_kj",
"proteine",
"lipidi",
"colesterolo",
"carboidrati_disponibili",
"amido",
"zuccheri_solubili",
"alcol",
"fibra_totale",
"fibra_solubile",
"fibra_insolubile",
"saccarosio",
"glucosio",
"fruttosio",
"lattosio",
"galattosio",
"maltosio",
"maltotriosio",
"raffinosio",
"fluoro",
"sodio",
"magnesio",
"fosforo",
"cloro",
"potassio",
"calcio",
"cromo",
"manganese",
"ferro",
"nichel",
"rame",
"zinco",
"selenio",
"iodio",
"carotenoidi_totali",
"alfa_carotene",
"beta_carotene",
"criptoxantina",
"licopene",
"luteina",
"retinolo",
"zeaxantina",
"vitamina_a_equivalenti_retinolo",
"tiamina",
"riboflavina",
"niacina",
"acido_pantotenico",
"vitamina_b6",
"biotina",
"folati",
"vitamina_b12",
"vitamina_c",
"vitamina_d",
"vitamina_e",
"alfa_tocoferolo",
"beta_tocoferolo",
"gamma_tocoferolo",
"delta_tocoferolo",
"vitamina_k",
"acidi_grassi_saturi",
"rapporto_polinsaturi_saturi",
"alanina",
"cistina",
"acido_aspartico",
"acido_glutammico",
"fenilalanina",
"glicina",
"istidina",
"isoleucina",
"lisina",
"leucina",
"metionina",
"prolina",
"arginina",
"serina",
"treonina",
"valina",
"triptofano",
"tirosina",
"indice_chimico",
"aminoacido_limitante",
"acido_caffeico",
"acido_citrico",
"acido_fitico",
"acido_malico",
"apigenina",
"attivita_antiossidante",
"kaempferolo",
"fitosteroli",
"frutto-oligosaccaridi",
"miricetina",
"polifenoli",
"quercetina",
"violaxantina"
]  # <-- modifica qui


df_filtrato = df_filtrato[COLONNE_SELEZIONATE2]

print(f"\nColonne selezionate: {COLONNE_SELEZIONATE2}")
print(f"Dimensioni dataframe filtrato: {df_filtrato.shape[0]} righe x {df_filtrato.shape[1]} colonne")

OUTPUT_FILE2 = "alimenti_filtrato_completo.csv"

# 4. Salva il nuovo CSV
df_filtrato.to_csv(OUTPUT_FILE2, sep=SEPARATOR, index=False)
print(f"\nFile salvato in: {OUTPUT_FILE2}")

